server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  accessLogEnabled: true
  serverRoot: C:\Users\jianjing\Desktop\go\zze-admin-go/resource/dist
  indexFiles: [ "index.html", "main.html" ]


logger:
  level: "all"
  stdout: true

database:
  logger:
    level: "all"
    stdout: "true"
  default:
    type: mysql
    link: "mysql:testuser:Qq125346@tcp(rm-cn-uax3gnrwd000bto.rwlb.rds.aliyuncs.com:3306)/zze_admin_go?loc=Local&parseTime=true"
    charset: utf8mb4
    maxIdle: "10"
    maxOpen: "300"
    debug: true

jwt:
  secret: vIIEngfamGZasdkseadgF9fe
  expire: 8h
