// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DrinkCombos is the golang structure of table drink_combos for DAO operations like Where/Data.
type DrinkCombos struct {
	g.Meta     `orm:"table:drink_combos, do:true"`
	Id         interface{} // 套餐ID
	DrinkName  interface{} // 酒水名称
	TotalPrice interface{} // 酒水总价格
	ComboPrice interface{} // 套餐价格
	Creator    interface{} // 创建人
	CreatedAt  *gtime.Time // 创建时间
	UpdatedAt  *gtime.Time // 更新时间
	DeletedAt  *gtime.Time // 删除时间
	IsDisabled interface{} // 是否禁用/停售
}
