// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Drinks is the golang structure of table drinks for DAO operations like Where/Data.
type Drinks struct {
	g.Meta            `orm:"table:drinks, do:true"`
	Id                interface{} // 酒水种类ID
	Name              interface{} // 酒水名称
	SellingPrice      interface{} // 售价
	CreatedAt         *gtime.Time // 创建时间
	UpdatedAt         *gtime.Time // 更新时间
	PurchasePrice     interface{} // 进价
	IsIncludedInCombo interface{} // 是否包含在套餐中
}
