// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DrinkCombosDao is the data access object for table drink_combos.
type DrinkCombosDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns DrinkCombosColumns // columns contains all the column names of Table for convenient usage.
}

// DrinkCombosColumns defines and stores column names for table drink_combos.
type DrinkCombosColumns struct {
	Id         string // 套餐ID
	DrinkName  string // 酒水名称
	TotalPrice string // 酒水总价格
	ComboPrice string // 套餐价格
	Creator    string // 创建人
	CreatedAt  string // 创建时间
	UpdatedAt  string // 更新时间
	DeletedAt  string // 删除时间
	IsDisabled string // 是否禁用/停售
}

// drinkCombosColumns holds the columns for table drink_combos.
var drinkCombosColumns = DrinkCombosColumns{
	Id:         "id",
	DrinkName:  "drink_name",
	TotalPrice: "total_price",
	ComboPrice: "combo_price",
	Creator:    "creator",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
	IsDisabled: "is_disabled",
}

// NewDrinkCombosDao creates and returns a new DAO object for table data access.
func NewDrinkCombosDao() *DrinkCombosDao {
	return &DrinkCombosDao{
		group:   "default",
		table:   "drink_combos",
		columns: drinkCombosColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DrinkCombosDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *DrinkCombosDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *DrinkCombosDao) Columns() DrinkCombosColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *DrinkCombosDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DrinkCombosDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DrinkCombosDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
