// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IContext interface {
	Init(ctx context.Context) error
	RefreshCasbin(ctx context.Context) error
	Ctx() *model.ServiceContext
}

var localContext IContext

func Context() IContext {
	if localContext == nil {
		panic("implement not found for interface IContext, forgot register?")
	}
	return localContext
}

func RegisterContext(i IContext) {
	localContext = i
}
