// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalDrinksDao is internal type for wrapping internal DAO implements.
type internalDrinksDao = *internal.DrinksDao

// drinksDao is the data access object for table drinks.
// You can define custom methods on it to extend its functionality as you wish.
type drinksDao struct {
	internalDrinksDao
}

var (
	// Drinks is globally public accessible object for table drinks operations.
	Drinks = drinksDao{
		internal.NewDrinksDao(),
	}
)

// Fill with you ideas below.
