// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devops-super/internal/dao/internal"
)

// internalDrinkCombosDao is internal type for wrapping internal DAO implements.
type internalDrinkCombosDao = *internal.DrinkCombosDao

// drinkCombosDao is the data access object for table drink_combos.
// You can define custom methods on it to extend its functionality as you wish.
type drinkCombosDao struct {
	internalDrinkCombosDao
}

var (
	// DrinkCombos is globally public accessible object for table drink_combos operations.
	DrinkCombos = drinkCombosDao{
		internal.NewDrinkCombosDao(),
	}
)

// Fill with you ideas below.
