// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Drinks is the golang structure for table drinks.
type Drinks struct {
	Id                int         `json:"id"                description:"酒水种类ID"`   // 酒水种类ID
	Name              string      `json:"name"              description:"酒水名称"`     // 酒水名称
	SellingPrice      float64     `json:"sellingPrice"      description:"售价"`       // 售价
	CreatedAt         *gtime.Time `json:"createdAt"         description:"创建时间"`     // 创建时间
	UpdatedAt         *gtime.Time `json:"updatedAt"         description:"更新时间"`     // 更新时间
	PurchasePrice     float64     `json:"purchasePrice"     description:"进价"`       // 进价
	IsIncludedInCombo int         `json:"isIncludedInCombo" description:"是否包含在套餐中"` // 是否包含在套餐中
}
