// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DrinkCombos is the golang structure for table drink_combos.
type DrinkCombos struct {
	Id         int         `json:"id"         description:"套餐ID"`    // 套餐ID
	DrinkName  string      `json:"drinkName"  description:"酒水名称"`    // 酒水名称
	TotalPrice float64     `json:"totalPrice" description:"酒水总价格"`   // 酒水总价格
	ComboPrice float64     `json:"comboPrice" description:"套餐价格"`    // 套餐价格
	Creator    string      `json:"creator"    description:"创建人"`     // 创建人
	CreatedAt  *gtime.Time `json:"createdAt"  description:"创建时间"`    // 创建时间
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:"更新时间"`    // 更新时间
	DeletedAt  *gtime.Time `json:"deletedAt"  description:"删除时间"`    // 删除时间
	IsDisabled int         `json:"isDisabled" description:"是否禁用/停售"` // 是否禁用/停售
}
